version: "3"
services:
  api-server:
    container_name: api-server
    image: soomanbaek/toquiz-api:1.0
    build: .
    depends_on:
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: soomanbaek/toquiz-redis:0.1
    ports:
      - "6379:6379"
    extra_hosts:
      - host.docker.internal:host-gateway